name: 'AdoreMe Tech PHPUnit Action'
description: 'Run PHPUnit tests (and optionally coverage)'
inputs:
  php-image:
    description: 'The PHP image to use'
    required: true
  reports-dir:
    description: 'Reports base directory'
    required: true
    default: 'build/reports'
  phpunit-report-file-name:
    description: 'PHPUnit report file name'
    required: true
    default: 'phpunit-junit.xml'
  enable-mysql:
    description: 'Enable MySQL'
    required: true
    default: 'false'
  run-migrations:
    description: 'Run migrations'
    required: true
    default: 'true'
  run-seeds:
    description: 'Run seeds'
    required: true
    default: 'true'
  enable-redis:
    description: 'Enable Redis'
    required: true
    default: 'false'
  enable-workers:
    description: 'Enable Workers'
    required: true
    default: 'false'
  workers-conf-path:
    description: 'Workers configuration file path'
    required: true
    default: 'ci/worker-confs/supervisor_dev_test_workers.conf'
  with-coverage:
    description: 'Run coverage'
    required: true
    default: 'true'
  coverage-report-file-name:
    description: 'Coverage report file name'
    required: true
    default: 'coverage-clover.xml'
  run-suites:
    description: 'Run specific suites. Pass suites as a comma separated list, no spaces (e.g. "UnitTests,IntegrationTests")'
    required: false
    default: ''
  verbose:
    description: 'Run PHPUnit in verbose mode'
    required: true
    default: 'false'
  min-line-coverage:
    description: 'Minimum percentage acceptable for line coverage'
    default: 0
  min-method-coverage:
    description: 'Minimum percentage acceptable for method coverage'
    default: 0
  enable-rabbitmq:
    description: 'Enable RabbitMQ'
    required: false
    default: 'false'
runs:
  using: 'composite'
  steps:
    - name: 'Start MySql'
      id: start-mysql
      if: ${{ inputs.enable-mysql == 'true' }}
      uses: adore-me/gha-mysql@v0.0.10

    - name: 'Start Redis'
      id: start-redis
      if: ${{ inputs.enable-redis == 'true' }}
      uses: adore-me/gha-redis@v0.0.4

    - name: 'Start RabbitMQ'
      id: start-rabbitmq
      if: ${{ inputs.enable-rabbitmq == 'true' }}
      uses: adore-me/gha-rabbitmq@v0.0.3

    - name: 'Run PHPUnit'
      id: phpunit
      run: $GITHUB_ACTION_PATH/phpunit.sh
      shell: bash
      env:
        INPUT_PHP_IMAGE: ${{ inputs.php-image }}
        MYSQL_CONTAINER_IP: ${{ steps.start-mysql.outputs.container-ip }}
        REDIS_CONTAINER_IP: ${{ steps.start-redis.outputs.container-ip }}
        INPUT_PHPUNIT_REPORT_PATH: '${{ inputs.reports-dir }}/${{ inputs.phpunit-report-file-name }}'
        INPUT_ENABLE_MYSQL: ${{ inputs.enable-mysql }}
        INPUT_RUN_MIGRATIONS: ${{ inputs.run-migrations }}
        INPUT_RUN_SEEDS: ${{ inputs.run-seeds }}
        INPUT_ENABLE_REDIS: ${{ inputs.enable-redis }}
        INPUT_ENABLE_WORKERS: ${{ inputs.enable-workers }}
        INPUT_WORKERS_CONF_PATH: ${{ inputs.workers-conf-path }}
        INPUT_WITH_COVERAGE: ${{ inputs.with-coverage }}
        INPUT_COVERAGE_REPORT_PATH: '${{ inputs.reports-dir }}/${{ inputs.coverage-report-file-name }}'
        INPUT_RUN_SUITES: ${{ inputs.run-suites }}
        INPUT_VERBOSE: ${{ inputs.verbose }}
        RABBITMQ_CONTAINER_IP: ${{ steps.start-rabbitmq.outputs.container-ip }}
        INPUT_ENABLE_RABBITMQ: ${{ inputs.enable-rabbitmq }}

    - name: 'Notify commiter'
      if: always()
      uses: actions/github-script@v7.0.1
      with:
        script: |
          if (${{ steps.phpunit.outputs.phpunit-error }} == true) {
            github.rest.issues.createComment({
              issue_number: context.issue.number,
              owner: context.repo.owner,
              repo: context.repo.repo,
              body: `@${{ github.event.pull_request.user.login }}<br />⚠ PHPUnit has errors.<br /><details><summary>Details</summary>${{ steps.phpunit.outputs.phpunit-error-message }}</details>`
            })
            github.rest.issues.addLabels({
              issue_number: context.issue.number,
              owner: context.repo.owner,
              repo: context.repo.repo,
              labels: ['phpunit-env-error']
            })
          }

    - name: 'Publish PHPUnit Results'
      if: always()
      uses: EnricoMi/publish-unit-test-result-action@v2.15.1
      with:
        check_name: 'PHPUnit'
        comment_title: 'PHPUnit Results'
        report_individual_runs: true
        junit_files: '${{ inputs.reports-dir }}/${{ inputs.phpunit-report-file-name }}'

    - name: 'Publish Coverage'
      if: ${{ always() && inputs.with-coverage != 'false' }}
      uses: lucassabreu/comment-coverage-clover@v0.12.0
      with:
        file: '${{ inputs.reports-dir }}/${{ inputs.coverage-report-file-name }}'
        dir-prefix: '/var/www'
        min-line-coverage: '${{ inputs.min-line-coverage }}'
        min-method-coverage: '${{ inputs.min-method-coverage }}'
        
    - name: 'Save PHPUnit artifacts'
      if: always()
      uses: actions/upload-artifact@v4.3.1
      with:
        name: phpunit-artifacts
        path: ${{ inputs.reports-dir }}

    - name: 'Stop MySql'
      if: ${{ inputs.enable-mysql == 'true' }}
      shell: bash
      run: |
        docker stop mysql -t 0 || true
        docker rm mysql || true

    - name: 'Stop Redis'
      if: ${{ inputs.enable-redis == 'true' }}
      shell: bash
      run: |
        docker stop redis -t 0 || true
        docker rm redis || true

    - name: 'Stop Nginx'
      if: always()
      shell: bash
      run: |
        docker stop nginx-fpm-alpine -t 0 || true
        docker rm nginx-fpm-alpine || true
